{   'active': False,
    'author': u'ADHOC SA',
    'category': 'base.module_category_hidden',
    'data': [   u'security/openacademy_group.xml',
                u'view/course_view.xml',
                u'view/session_view.xml',
                u'view/partner_view.xml',
                u'data/course_properties.xml',
                u'data/session_properties.xml',
                u'data/partner_properties.xml',
                u'data/course_track.xml',
                u'data/session_track.xml',
                u'data/partner_track.xml',
                'security/ir.model.access.csv',
                u'view/openacademy_menuitem.xml',
                u'view/openacademy_actions.xml'],
    'depends': [u'mail'],
    'description': u'Manage trainings',
    'installable': True,
    'license': 'AGPL-3',
    'name': 'openacademy',
    'test': [],
    'version': u'1.1',
    'website': ''}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
